import "~/styles/globals.css";

import { IconArrowUpRight, IconLink, IconMenu } from "@tabler/icons-react";
import { Unbounded, Work_Sans } from "next/font/google";
import Link from "next/link";
import { cn } from "~/lib/cn";
import { socials } from "~/lib/fake-db";
import ExternalLink from "./_components/external-link";
import NavbarItems from "./_components/navbar-items";
import { Button, buttonVariants } from "./_components/ui/button";
import {
  Sheet,
  SheetContent,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "./_components/ui/sheet";

const unbounded = Unbounded({
  subsets: ["latin"],
  variable: "--font-heading",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn(unbounded.variable, workSans.variable)}>
      <body className="flex min-h-screen flex-col bg-violet-200 font-body text-indigo-950 antialiased [text-wrap:pretty]">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

function Navbar() {
  return (
    <header className="sticky top-0 z-10 border-b border-b-indigo-950 bg-violet-200">
      <div className="mx-auto flex max-w-screen-2xl justify-between">
        <Link
          href="/"
          className={buttonVariants({
            size: "lg",
            variant: "ghost",
            class: "font-heading capitalize",
          })}
        >
          Shelly Liu
        </Link>

        <NavbarItems isDrawer={false} />

        <Sheet>
          <SheetTrigger className="block sm:hidden" asChild>
            <Button>
              <IconMenu />
              <span className="sr-only">Navigation menu</span>
            </Button>
          </SheetTrigger>

          <SheetContent>
            <SheetHeader>
              <SheetTitle>Navigation</SheetTitle>
            </SheetHeader>

            <NavbarItems isDrawer={true} />

            <SheetFooter>
              {socials.map(({ name, href }) => (
                <ExternalLink
                  key={name}
                  href={href}
                  className={buttonVariants({
                    variant: "secondary",
                    size: "icon",
                  })}
                >
                  <IconLink size={20} />
                  <span className="sr-only">
                    Link to Shelly&apos;s {name} page
                  </span>
                </ExternalLink>
              ))}
            </SheetFooter>
          </SheetContent>
        </Sheet>
      </div>
    </header>
  );
}

function Footer() {
  const date = new Date();
  const year = date.getFullYear();

  return (
    <footer className="border-b-8 border-b-indigo-950">
      <div className="mx-auto flex max-w-screen-md flex-col justify-between gap-6 p-6 sm:flex-row sm:items-center md:py-12">
        <div className="space-y-1.5">
          <p className="font-heading text-lg font-medium">
            &copy; Shelly Liu {year}
          </p>

          <div className="flex flex-col items-start gap-1.5 text-xs sm:flex-row sm:items-center">
            <Link
              href="/"
              className={cn(buttonVariants({ variant: "link" }), "p-0")}
            >
              Privacy
            </Link>

            <span className="hidden sm:block">&middot;</span>

            <ExternalLink href="/" className="gap-0.5">
              Built by Mike
              <IconArrowUpRight size={14} />
            </ExternalLink>
          </div>
        </div>

        <div className="flex gap-1.5">
          {socials.map(({ name, href }) => (
            <ExternalLink
              key={name}
              href={href}
              className={buttonVariants({ size: "icon" })}
            >
              <IconLink size={20} />
              <span className="sr-only">Link to Shelly&apos;s {name} page</span>
            </ExternalLink>
          ))}
        </div>
      </div>
    </footer>
  );
}
