import "~/styles/globals.css";

import { Montserrat, Unbounded } from "next/font/google";
import Link from "next/link";
import { cn } from "~/lib/cn";
import NavbarItems from "./_components/navbar-items";
import { buttonVariants } from "./_components/ui/button";

const unbounded = Unbounded({
  subsets: ["latin"],
  variable: "--font-heading",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn(unbounded.variable, montserrat.variable)}>
      <body className="min-h-screen bg-violet-200 font-body text-indigo-950 antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}

function Navbar() {
  return (
    <header className="sticky top-0 z-10 border-b border-b-indigo-950 bg-violet-200">
      <div className="mx-auto flex max-w-screen-2xl justify-between">
        <Link
          href="/"
          className={buttonVariants({
            size: "lg",
            variant: "ghost",
            class: "font-heading capitalize",
          })}
        >
          Shelly Liu
        </Link>

        <NavbarItems />
      </div>
    </header>
  );
}
